In [19]:
#Import modul
from PIL import Image                                   
import cv2                                              
import numpy as np                                      
import matplotlib.pyplot as plt 

In [20]:
import os
os.getcwd()

'C:\\Users\\Changcut\\Desktop\\ParkingSlot\\Slot'

In [21]:
image = cv2.imread("Gambar/tes1.jpg") 
image = cv2.resize(image, (1024,600), interpolation = cv2.INTER_AREA) 
state = 0 
sum_rows = 0 
sum_slots = []  
font = cv2.FONT_HERSHEY_PLAIN 

In [22]:
ROI_slot =[]  
imges = image.copy() 
original_clone = image.copy()  
clone = Image.fromarray(original_clone)

In [23]:
#PAKE INI
def coordinate(event,x,y,flags,param):
    global point,click,keyPoint,tAwal,tAkhir,indexClick
    
    if event==cv2.EVENT_LBUTTONDOWN:
        point=(x,y)
        keyPoint.append(point)
        print(keyPoint)
        click = click + 1
        if click==1:
            tAkhir = tAwal + 1
            cv2.line(image,keyPoint[tAwal],keyPoint[tAkhir],(0,0,255),2)
        elif click==2:
            tAwal = tAkhir
            tAkhir = tAkhir + 1
            cv2.line(image,keyPoint[tAwal],keyPoint[tAkhir],(0,0,255),2)
        elif click==3:
            tAwal = tAkhir
            tAkhir = tAkhir + 1
            cv2.line(image,keyPoint[tAwal],keyPoint[tAkhir],(0,0,255),2)
            cv2.line(image,keyPoint[tAwal-2],keyPoint[tAkhir],(0,0,255),2)
            click = 1
            

In [24]:
#Ambil jumlah lahan dan slot parkir
while True:                                             
    # display the image and wait for a keypress 
    one = str(sum_rows) 
    two = str(sum_slots) 
    three = str(state+1) 
    cv2.putText(image,(one+"="+two), (100,100), font, 2, (0,0,255),1) 
    cv2.putText(image,three, (30,30), font, 2, (0,0,255),1) 
    cv2.imshow("Image",image)                          
    key = cv2.waitKey(1) & 0xFF                         
    if key == ord("p"):  
        sum_rows = sum_rows +1 
        sum_slots.append(0) 
        image = original_clone.copy() 
    if key == ord("l"): 
        state=state+1 
        if state==sum_rows: 
            state = 0 
        image = original_clone.copy() 
    if key == ord("o"): 
        sum_slots[state] = sum_slots[state] +1 
        image = original_clone.copy() 
    elif key == ord("c"):                               
        break                                           
cv2.destroyAllWindows()

In [ ]:
#Mulai plot slot
image = original_clone.copy()
for row in range(sum_rows):
    point = []
    keyPoint = []
    click = -1
    tAkhir = 0
    tAwal = 0

    cv2.namedWindow('image')
    cv2.setMouseCallback('image',coordinate)

    while True:
        cv2.imshow('image',image)
        if cv2.waitKey(1) & 0xFF == ord('c'):
            break
    cv2.destroyAllWindows()
    
    ROI_slot.append([])
    for i in range(sum_slots[row]):
        ROI_slot[row].append([])
        ROI_slot[row][i].append([keyPoint[0+i+i][0],keyPoint[0+i+i][1]])
        ROI_slot[row][i].append([keyPoint[1+i+i][0],keyPoint[1+i+i][1]])
        ROI_slot[row][i].append([keyPoint[2+i+i][0],keyPoint[2+i+i][1]])
        ROI_slot[row][i].append([keyPoint[3+i+i][0],keyPoint[3+i+i][1]])

[(622, 65)]
[(622, 65), (620, 41)]
[(622, 65), (620, 41), (561, 40)]
[(622, 65), (620, 41), (561, 40), (558, 64)]
[(622, 65), (620, 41), (561, 40), (558, 64), (499, 68)]
[(622, 65), (620, 41), (561, 40), (558, 64), (499, 68), (507, 41)]
[(622, 65), (620, 41), (561, 40), (558, 64), (499, 68), (507, 41), (446, 39)]
[(622, 65), (620, 41), (561, 40), (558, 64), (499, 68), (507, 41), (446, 39), (431, 65)]
[(622, 65), (620, 41), (561, 40), (558, 64), (499, 68), (507, 41), (446, 39), (431, 65), (378, 64)]
[(622, 65), (620, 41), (561, 40), (558, 64), (499, 68), (507, 41), (446, 39), (431, 65), (378, 64), (389, 40)]
[(622, 65), (620, 41), (561, 40), (558, 64), (499, 68), (507, 41), (446, 39), (431, 65), (378, 64), (389, 40), (336, 38)]
[(622, 65), (620, 41), (561, 40), (558, 64), (499, 68), (507, 41), (446, 39), (431, 65), (378, 64), (389, 40), (336, 38), (325, 61)]
[(622, 65), (620, 41), (561, 40), (558, 64), (499, 68), (507, 41), (446, 39), (431, 65), (378, 64), (389, 40), (336, 38), (325, 61

[(1020, 207), (978, 156), (894, 160), (937, 213), (835, 213), (804, 163), (720, 159), (730, 213), (637, 211), (631, 162), (541, 158), (534, 208), (444, 206), (456, 159), (372, 154), (350, 203), (260, 200), (287, 154), (200, 151), (169, 202), (68, 198)]
[(1020, 207), (978, 156), (894, 160), (937, 213), (835, 213), (804, 163), (720, 159), (730, 213), (637, 211), (631, 162), (541, 158), (534, 208), (444, 206), (456, 159), (372, 154), (350, 203), (260, 200), (287, 154), (200, 151), (169, 202), (68, 198), (113, 150)]
[(1020, 207), (978, 156), (894, 160), (937, 213), (835, 213), (804, 163), (720, 159), (730, 213), (637, 211), (631, 162), (541, 158), (534, 208), (444, 206), (456, 159), (372, 154), (350, 203), (260, 200), (287, 154), (200, 151), (169, 202), (68, 198), (113, 150), (33, 143)]
[(1020, 207), (978, 156), (894, 160), (937, 213), (835, 213), (804, 163), (720, 159), (730, 213), (637, 211), (631, 162), (541, 158), (534, 208), (444, 206), (456, 159), (372, 154), (350, 203), (260, 200), 

In [11]:
ROI_slot

[[[[781, 393], [729, 288], [536, 267], [423, 329]],
  [[536, 267], [423, 329], [235, 296], [403, 257]],
  [[235, 296], [403, 257], [305, 249], [110, 277]]]]

In [15]:
import numpy as np

arr = np.array(ROI_slot)
print(arr)

[[[[779 391]
   [730 288]
   [538 269]
   [424 328]]

  [[538 269]
   [424 328]
   [238 296]
   [402 257]]

  [[238 296]
   [402 257]
   [307 249]
   [113 276]]

  [[307 249]
   [113 276]
   [ 34 265]
   [221 245]]

  [[ 34 265]
   [221 245]
   [158 240]
   [  4 253]]

  [[158 240]
   [  4 253]
   [  2 244]
   [108 236]]]]


In [17]:
#Export ke npy
from numpy import save

save("Tes.npy",arr)