In [21]:
#Import modul
from PIL import Image                                   
import cv2                                              
import numpy as np                                      
import matplotlib.pyplot as plt 

In [22]:
import os
os.getcwd()

'C:\\Users\\Changcut\\Desktop\\ParkingSlot\\Slot'

In [66]:
image = cv2.imread("data/CNR/samples/cam9.jpg") 
image = cv2.resize(image, (image.shape[1],image.shape[0]), interpolation = cv2.INTER_AREA) 
state = 0 
sum_rows = 0 
sum_slots = []  
font = cv2.FONT_HERSHEY_PLAIN

In [67]:
ROI_slot =[]  
imges = image.copy() 
original_clone = image.copy()  
clone = Image.fromarray(original_clone)

In [68]:
#PAKE INI
def coordinate(event,x,y,flags,param):
    global point,click,keyPoint,tAwal,tAkhir,indexClick
    
    if event==cv2.EVENT_LBUTTONDOWN:
        point=(x,y)
        keyPoint.append(point)
        print(keyPoint)
        click = click + 1
        if click==1:
            tAkhir = tAwal + 1
            cv2.line(image,keyPoint[tAwal],keyPoint[tAkhir],(0,0,255),2)
        elif click==2:
            tAwal = tAkhir
            tAkhir = tAkhir + 1
            cv2.line(image,keyPoint[tAwal],keyPoint[tAkhir],(0,0,255),2)
        elif click==3:
            tAwal = tAkhir
            tAkhir = tAkhir + 1
            cv2.line(image,keyPoint[tAwal],keyPoint[tAkhir],(0,0,255),2)
            cv2.line(image,keyPoint[tAwal-2],keyPoint[tAkhir],(0,0,255),2)
            click = 1
            

In [69]:
#Ambil jumlah lahan dan slot parkir
while True:                                             
    # display the image and wait for a keypress 
    one = str(sum_rows) 
    two = str(sum_slots) 
    three = str(state+1) 
    cv2.putText(image,(one+"="+two), (100,100), font, 2, (0,0,255),1) 
    cv2.putText(image,three, (30,30), font, 2, (0,0,255),1) 
    cv2.imshow("Image",image)                          
    key = cv2.waitKey(1) & 0xFF                         
    if key == ord("p"):  
        sum_rows = sum_rows +1 
        sum_slots.append(0) 
        image = original_clone.copy() 
    if key == ord("l"): 
        state=state+1 
        if state==sum_rows: 
            state = 0 
        image = original_clone.copy() 
    if key == ord("o"): 
        sum_slots[state] = sum_slots[state] +1 
        image = original_clone.copy() 
    elif key == ord("c"):                               
        break                                           
cv2.destroyAllWindows()

In [70]:
#Mulai plot slot
image = original_clone.copy()
for row in range(sum_rows):
    point = []
    keyPoint = []
    click = -1
    tAkhir = 0
    tAwal = 0

    cv2.namedWindow('image')
    cv2.setMouseCallback('image',coordinate)

    while True:
        cv2.imshow('image',image)
        if cv2.waitKey(1) & 0xFF == ord('c'):
            break
    cv2.destroyAllWindows()
    
    ROI_slot.append([])
    for i in range(sum_slots[row]):
        ROI_slot[row].append([])
        ROI_slot[row][i].append([keyPoint[0+i+i][0],keyPoint[0+i+i][1]])
        ROI_slot[row][i].append([keyPoint[1+i+i][0],keyPoint[1+i+i][1]])
        ROI_slot[row][i].append([keyPoint[2+i+i][0],keyPoint[2+i+i][1]])
        ROI_slot[row][i].append([keyPoint[3+i+i][0],keyPoint[3+i+i][1]])

[(969, 103)]
[(969, 103), (970, 70)]
[(969, 103), (970, 70), (911, 66)]
[(969, 103), (970, 70), (911, 66), (904, 96)]
[(969, 103), (970, 70), (911, 66), (904, 96), (841, 92)]
[(969, 103), (970, 70), (911, 66), (904, 96), (841, 92), (856, 65)]
[(969, 103), (970, 70), (911, 66), (904, 96), (841, 92), (856, 65), (796, 61)]
[(969, 103), (970, 70), (911, 66), (904, 96), (841, 92), (856, 65), (796, 61), (782, 86)]
[(969, 103), (970, 70), (911, 66), (904, 96), (841, 92), (856, 65), (796, 61), (782, 86), (725, 84)]
[(969, 103), (970, 70), (911, 66), (904, 96), (841, 92), (856, 65), (796, 61), (782, 86), (725, 84), (745, 56)]
[(969, 103), (970, 70), (911, 66), (904, 96), (841, 92), (856, 65), (796, 61), (782, 86), (725, 84), (745, 56), (695, 52)]
[(969, 103), (970, 70), (911, 66), (904, 96), (841, 92), (856, 65), (796, 61), (782, 86), (725, 84), (745, 56), (695, 52), (670, 78)]
[(969, 103), (970, 70), (911, 66), (904, 96), (841, 92), (856, 65), (796, 61), (782, 86), (725, 84), (745, 56), (695, 

In [71]:
ROI_slot

[[[[969, 103], [970, 70], [911, 66], [904, 96]],
  [[911, 66], [904, 96], [841, 92], [856, 65]],
  [[841, 92], [856, 65], [796, 61], [782, 86]],
  [[796, 61], [782, 86], [725, 84], [745, 56]],
  [[725, 84], [745, 56], [695, 52], [670, 78]],
  [[695, 52], [670, 78], [616, 76], [644, 51]],
  [[616, 76], [644, 51], [597, 46], [566, 72]]],
 [[[962, 191], [967, 154], [890, 146], [878, 181]],
  [[890, 146], [878, 181], [797, 173], [816, 140]],
  [[797, 173], [816, 140], [745, 135], [720, 165]],
  [[745, 135], [720, 165], [645, 160], [679, 126]],
  [[645, 160], [679, 126], [626, 118], [582, 152]],
  [[626, 118], [582, 152], [525, 148], [566, 114]],
  [[525, 148], [566, 114], [509, 105], [464, 138]]],
 [[[950, 299], [959, 229], [863, 219], [840, 285]],
  [[863, 219], [840, 285], [746, 275], [781, 208]],
  [[746, 275], [781, 208], [699, 200], [654, 261]],
  [[699, 200], [654, 261], [570, 252], [616, 193]],
  [[570, 252], [616, 193], [550, 185], [497, 238]],
  [[550, 185], [497, 238], [415, 227]

In [77]:
import numpy as np

arr = np.array(ROI_slot)
print(arr)

[[[[969 103]
   [970  70]
   [911  66]
   [904  96]]

  [[911  66]
   [904  96]
   [841  92]
   [856  65]]

  [[841  92]
   [856  65]
   [796  61]
   [782  86]]

  [[796  61]
   [782  86]
   [725  84]
   [745  56]]

  [[725  84]
   [745  56]
   [695  52]
   [670  78]]

  [[695  52]
   [670  78]
   [616  76]
   [644  51]]

  [[616  76]
   [644  51]
   [597  46]
   [566  72]]]


 [[[962 191]
   [967 154]
   [890 146]
   [878 181]]

  [[890 146]
   [878 181]
   [797 173]
   [816 140]]

  [[797 173]
   [816 140]
   [745 135]
   [720 165]]

  [[745 135]
   [720 165]
   [645 160]
   [679 126]]

  [[645 160]
   [679 126]
   [626 118]
   [582 152]]

  [[626 118]
   [582 152]
   [525 148]
   [566 114]]

  [[525 148]
   [566 114]
   [509 105]
   [464 138]]]


 [[[950 299]
   [959 229]
   [863 219]
   [840 285]]

  [[863 219]
   [840 285]
   [746 275]
   [781 208]]

  [[746 275]
   [781 208]
   [699 200]
   [654 261]]

  [[699 200]
   [654 261]
   [570 252]
   [616 193]]

  [[570 252]
   [616 193

In [78]:
type(arr[0][0][0])

numpy.ndarray

In [74]:
#Export ke npy
from numpy import save

save("data/CNR/coordinate/cam9.npy",arr)