In [9]:
#Import modul
from PIL import Image                                   
import cv2                                              
import numpy as np                                      
import matplotlib.pyplot as plt 

In [10]:
cap = cv2.VideoCapture("data/Polban/samples/vid1.mp4")
while(cap.isOpened()):
    ret, frame = cap.read()
    if ret == False:
        break
    cv2.imwrite("data/Polban/samples/vid1Frame.jpg",frame)
cap.release()
cv2.destroyAllWindows()

In [18]:
vid1Frame = cv2.imread("data/Polban/samples/vid1Frame.jpg")
vid1Frame = cv2.resize(vid1Frame, (vid1Frame.shape[1],vid1Frame.shape[0]), interpolation = cv2.INTER_AREA) 
cv2.imshow('Frame',vid1Frame)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
vid1Frame.shape

(600, 1024, 3)

In [20]:
state = 0 
sum_rows = 0 
sum_slots = []  
font = cv2.FONT_HERSHEY_PLAIN 

ROI_slot =[]
original_clone = vid1Frame.copy()

In [21]:
#PAKE INI
def coordinate(event,x,y,flags,param):
    global point,click,keyPoint,tAwal,tAkhir,indexClick
    
    if event==cv2.EVENT_LBUTTONDOWN:
        point=(x,y)
        keyPoint.append(point)
        print(keyPoint)
        click = click + 1
        if click==1:
            tAkhir = tAwal + 1
            cv2.line(vid1Frame,keyPoint[tAwal],keyPoint[tAkhir],(0,0,255),2)
        elif click==2:
            tAwal = tAkhir
            tAkhir = tAkhir + 1
            cv2.line(vid1Frame,keyPoint[tAwal],keyPoint[tAkhir],(0,0,255),2)
        elif click==3:
            tAwal = tAkhir
            tAkhir = tAkhir + 1
            cv2.line(vid1Frame,keyPoint[tAwal],keyPoint[tAkhir],(0,0,255),2)
            cv2.line(vid1Frame,keyPoint[tAwal-2],keyPoint[tAkhir],(0,0,255),2)
            click = 1

In [22]:
#Ambil jumlah lahan dan slot parkir
while True:                                             
    # display the image and wait for a keypress 
    one = str(sum_rows) 
    two = str(sum_slots) 
    three = str(state+1) 
    cv2.putText(vid1Frame,(one+"="+two), (100,100), font, 2, (0,0,255),1) 
    cv2.putText(vid1Frame,three, (30,30), font, 2, (0,0,255),1) 
    cv2.imshow("Frame",vid1Frame)                          
    key = cv2.waitKey(1) & 0xFF                         
    if key == ord("p"):  
        sum_rows = sum_rows +1 
        sum_slots.append(0) 
        vid1Frame = original_clone.copy() 
    if key == ord("l"): 
        state=state+1 
        if state==sum_rows: 
            state = 0 
        vid1Frame = original_clone.copy() 
    if key == ord("o"): 
        sum_slots[state] = sum_slots[state] +1 
        vid1Frame = original_clone.copy() 
    elif key == ord("c"):                               
        break                                           
cv2.destroyAllWindows()

In [23]:
#Mulai plot slot
vid1Frame = original_clone.copy()
for row in range(sum_rows):
    point = []
    keyPoint = []
    click = -1
    tAkhir = 0
    tAwal = 0

    cv2.namedWindow('frame')
    cv2.setMouseCallback('frame',coordinate)

    while True:
        cv2.imshow('frame',vid1Frame)
        if cv2.waitKey(1) & 0xFF == ord('c'):
            break
    cv2.destroyAllWindows()
    
    ROI_slot.append([])
    for i in range(sum_slots[row]):
        ROI_slot[row].append([])
        ROI_slot[row][i].append([keyPoint[0+i+i][0],keyPoint[0+i+i][1]])
        ROI_slot[row][i].append([keyPoint[1+i+i][0],keyPoint[1+i+i][1]])
        ROI_slot[row][i].append([keyPoint[2+i+i][0],keyPoint[2+i+i][1]])
        ROI_slot[row][i].append([keyPoint[3+i+i][0],keyPoint[3+i+i][1]])

[(2, 440)]
[(2, 440), (88, 354)]
[(2, 440), (88, 354), (233, 341)]
[(2, 440), (88, 354), (233, 341), (108, 442)]
[(2, 440), (88, 354), (233, 341), (108, 442), (277, 412)]
[(2, 440), (88, 354), (233, 341), (108, 442), (277, 412), (368, 318)]
[(2, 440), (88, 354), (233, 341), (108, 442), (277, 412), (368, 318), (506, 293)]
[(2, 440), (88, 354), (233, 341), (108, 442), (277, 412), (368, 318), (506, 293), (459, 375)]
[(2, 440), (88, 354), (233, 341), (108, 442), (277, 412), (368, 318), (506, 293), (459, 375), (623, 343)]
[(2, 440), (88, 354), (233, 341), (108, 442), (277, 412), (368, 318), (506, 293), (459, 375), (623, 343), (627, 272)]
[(2, 440), (88, 354), (233, 341), (108, 442), (277, 412), (368, 318), (506, 293), (459, 375), (623, 343), (627, 272), (737, 256)]
[(2, 440), (88, 354), (233, 341), (108, 442), (277, 412), (368, 318), (506, 293), (459, 375), (623, 343), (627, 272), (737, 256), (770, 311)]
[(2, 440), (88, 354), (233, 341), (108, 442), (277, 412), (368, 318), (506, 293), (459,

In [24]:
ROI_slot

[[[[2, 440], [88, 354], [233, 341], [108, 442]],
  [[233, 341], [108, 442], [277, 412], [368, 318]],
  [[277, 412], [368, 318], [506, 293], [459, 375]],
  [[506, 293], [459, 375], [623, 343], [627, 272]],
  [[623, 343], [627, 272], [737, 256], [770, 311]],
  [[737, 256], [770, 311], [889, 283], [833, 238]],
  [[889, 283], [833, 238], [913, 219], [986, 261]],
  [[913, 219], [986, 261], [1023, 250], [991, 210]]]]

In [25]:
import numpy as np

arr = np.array(ROI_slot)
print(arr)

[[[[   2  440]
   [  88  354]
   [ 233  341]
   [ 108  442]]

  [[ 233  341]
   [ 108  442]
   [ 277  412]
   [ 368  318]]

  [[ 277  412]
   [ 368  318]
   [ 506  293]
   [ 459  375]]

  [[ 506  293]
   [ 459  375]
   [ 623  343]
   [ 627  272]]

  [[ 623  343]
   [ 627  272]
   [ 737  256]
   [ 770  311]]

  [[ 737  256]
   [ 770  311]
   [ 889  283]
   [ 833  238]]

  [[ 889  283]
   [ 833  238]
   [ 913  219]
   [ 986  261]]

  [[ 913  219]
   [ 986  261]
   [1023  250]
   [ 991  210]]]]


In [26]:
#Export ke npy
from numpy import save

save("data/Polban/coordinate/vid1.npy",arr)